노트북 데이터 디렉토리 수정
ProtossDragoon/PlankHyundong pull request #19
Opened 2022-09-18 10:40 UTC by yyongjae

2022-09-19 03:38 UTC, ProtossDragoon requested changes

2022-09-19 03:38 UTC, ProtossDragoon commented on README.md
> +<a href="https://colab.research.google.com/github/yyongjae/PlankHyundong/blob/main/notebooks/sampling_colab.ipynb">
이거 노트북 경로 잘못된거 맞나?

2022-11-04 17:33 UTC, ProtossDragoon commented on README.md
> +<a href="https://colab.research.google.com/github/yyongjae/PlankHyundong/blob/main/notebooks/sampling_colab.ipynb">
이거 확인점요

2022-11-25 15:59 UTC, yyongjae commented on README.md
> +<a href="https://colab.research.google.com/github/yyongjae/PlankHyundong/blob/main/notebooks/sampling_colab.ipynb">
못봤네 그 wandb 없는 걸로 내 레포에 하나 만들었슴다

2022-11-26 07:53 UTC, merged