🐛 노트북 실행시 colmap, nerf에 발생하는 오류 수정 #20
ProtossDragoon/PlankHyundong pull request #22
Opened 2022-11-25 15:40 UTC by yyongjae

## Details

- colmap의 레포를 clone받는 셀에서 최신 버전이 아닌 구버전의 colmap을 가져오도록 변경함
- nerf 레포를 clone받는 셀에서 경로 문제가 생겨 경로 수정을 함

2022-11-25 15:44 UTC, yyongjae commented
#20

2022-11-25 16:44 UTC, ProtossDragoon requested changes

2022-11-25 16:44 UTC, ProtossDragoon commented on README.md
> +<a href="https://colab.research.google.com/github/yyongjae/PlankHyundong/blob/main/notebooks/sampling_colab.ipynb">
링크 확인점

2022-11-25 16:44 UTC, ProtossDragoon commented on notebooks/colmap_colab.ipynb
> +        "!git reset --hard 5879f41fb89d9ac71d977ae6cf898350c77cd59f\n",
하드리셋도 좋은 방법이지만 특정 릴리즈 버전으로 체크아웃하면 안될까? e.g. `git checkout tags/3.x`

2022-11-25 16:44 UTC, ProtossDragoon commented on notebooks/extract_mesh_colab.ipynb
> +        "basedir = '/content/drive/MyDrive/PlankHyundong/data/logs'\n",
좋다 이거 갈아엎고싶었는데

2022-11-25 17:53 UTC, yyongjae commented on README.md
> +<a href="https://colab.research.google.com/github/yyongjae/PlankHyundong/blob/main/notebooks/sampling_colab.ipynb">
수정완

2022-11-25 18:01 UTC, yyongjae commented on notebooks/colmap_colab.ipynb
> +        "!git reset --hard 5879f41fb89d9ac71d977ae6cf898350c77cd59f\n",
수정은했는데 실행하려면 시간 또 걸려서 아침에 확인해보겠읍니다

2022-11-26 07:53 UTC, ProtossDragoon approved these changes

2022-11-26 07:53 UTC, merged