✨샘플링 노트북 추가
ProtossDragoon/PlankHyundong pull request #6
Opened 2022-08-23 09:09 UTC by yyongjae

2022-08-24 00:33 UTC, ProtossDragoon commented
utils 디렉터리에 있는 video sampling .py 파일만 삭제해서 다시 보내주라!

2022-08-28 10:26 UTC, ProtossDragoon commented
@all-contributors please add @yyongjae for maintenance

2022-09-13 00:26 UTC, ProtossDragoon requested changes

2022-09-13 00:26 UTC, ProtossDragoon commented on notebooks/nerf_colab.ipynb
> -  "nbformat": 4,
이 파일 완전 더미로 변경된것같아
아마 나는 COLAB 에서 작업했는데 로컬 주피터 노트북에서 열어서 diff 발생한듯?
git add 에서 제외시키고 커밋!

2022-09-13 00:26 UTC, ProtossDragoon commented on nerf_quick_start.ipynb
> +    "path = 'content/PlankHyundong/data'\n",
이 경로 관련해서 우리 readme 에 없어서 설명을 조금 더 해주는게 좋을듯한데
어떻게 하는게 좋을까 모르겠어

2022-09-13 00:26 UTC, ProtossDragoon commented on nerf_quick_start.ipynb
> +    "config['']['maxiter'] = max_iter\n",
이거 뭐야??

2022-09-13 07:58 UTC, yyongjae commented on notebooks/nerf_colab.ipynb
> -  "nbformat": 4,
내가 건든거야??

2022-09-13 08:13 UTC, yyongjae commented on nerf_quick_start.ipynb
> +    "config['']['maxiter'] = max_iter\n",
config.txt 파일 만드려고 한건데 코드 바꼈음

2022-09-13 09:25 UTC, merged